import request from "supertest";
import { describe, expect, it } from "vitest";
import * as helper from "./helper/index";
const app = helper.postcodesioApplication();

describe("Scottish postcodes E2E", () => {
  describe("GET /scotland/postcodes/:postcode", () => {
    it("returns exact expected response for AB10 1AB", async () => {
      const expectedResponse = {
        postcode: "AB10 1AB",
        pc_compact: "AB101AB",
        postcode_district: "AB10",
        postcode_sector: "AB10 1",
        incode: "1AB",
        outcode: "AB10",
        user_type: "large",
        date_of_introduction: "11/7/2011 00:00:00",
        date_of_deletion: null,
        linked_small_user_postcode: "AB10 1FF",
        longitude: -2.09692315,
        latitude: 57.14958998,
        eastings: 394235,
        northings: 806529,
        split_indicator: "N",
        grid_link_indicator: "Y",
        grid_link_positional_accuracy: "1",
        council_area: "Aberdeen City",
        electoral_ward: "George St/Harbour",
        registration_district: "S12000033",
        enterprise_region: "Aberdeen City and Shire",
        strategic_development_planning_area: "S11000001",
        local_government_district: "Aberdeen City",
        local_government_district_1991: "Aberdeen City",
        uk_parliamentary_constituency: "Aberdeen South",
        scottish_parliamentary_region: "North East Scotland",
        scottish_parliamentary_constituency: "Aberdeen Central",
        health_board_area: "Grampian",
        health_board_area_2006: "Grampian",
        health_board_area_1995: "Grampian",
        integration_authority: "Aberdeen City",
        output_area: "S00136377",
        output_area_2011: "S00090540",
        output_area_2001: "S00000036",
        output_area_1991: "6015AA21B",
        data_zone: "George Street - 02",
        data_zone_2011: "S01006646",
        data_zone_2001: "S01000125",
        intermediate_zone: "George Street",
        intermediate_zone_2011: "S02001261",
        intermediate_zone_2001: "S02000024",
        locality: "Aberdeen",
        locality_2020: "Aberdeen",
        locality_2001: "Aberdeen",
        locality_1991: "Aberdeen",
        settlement: "Aberdeen, Milltimber, and Peterculter",
        settlement_2020: null,
        settlement_2001: "Aberdeen",
        civil_parish: "Aberdeen",
        island: "Mainland of Scotland",
        national_park: null,
        travel_to_work_area: "Aberdeen",
        lau_level_1: "Aberdeen City",
        itl_level_2: "North Eastern Scotland",
        itl_level_3: "Aberdeen City and Aberdeenshire",
        urban_rural_6_fold: "1",
        urban_rural_8_fold: "1",
        scottish_index_of_multiple_deprivation: 3888,
        roa_community_planning_partnership: null,
        roa_local: null,
        census_household_count: null,
        census_household_count_2011: null,
        census_household_count_2001: null,
        census_household_count_1991: null,
        census_population_count: null,
        census_population_count_2011: null,
        census_population_count_2001: null,
        census_population_count_1991: null,
        never_digitised: null,
        codes: {
          council_area: "S12000033",
          electoral_ward: "S13002842",
          enterprise_region: "S09000001",
          local_government_district: "15",
          local_government_district_1991: "15",
          uk_parliamentary_constituency: "S14000061",
          scottish_parliamentary_region: "S17000026",
          scottish_parliamentary_constituency: "S16000151",
          health_board_area: "S08000020",
          health_board_area_2006: "S08000006",
          health_board_area_1995: "02",
          integration_authority: "S37000001",
          data_zone: "S01013627",
          data_zone_2011: "S01006646",
          data_zone_2001: "S01000125",
          intermediate_zone: "S02002541",
          intermediate_zone_2011: "S02001261",
          intermediate_zone_2001: "S02000024",
          locality: "S52000002",
          settlement: "S53000002",
          civil_parish: "S35000005",
          island: "000",
          national_park: null,
          travel_to_work_area: "S22000047",
          lau_level_1: "S30000026",
          itl_level_2: "TLM5",
          itl_level_3: "TLM50",
          registration_district: "S12000033",
          strategic_development_planning_area: "S11000001",
          roa_community_planning_partnership: null,
          roa_local: null,
        },
      };

      const response = await request(app)
        .get("/scotland/postcodes/AB10%201AB")
        .expect("Content-Type", /json/)
        .expect(200);
      expect(response.body.status).toBe(200);
      expect(response.body.result).toEqual(expectedResponse);
    });
  });
});
