extends:
  - recommended

apis:
  idealpostcodes:
    root: ./openapi/openapi.yaml

theme:
  openapi:
    htmlTemplate: ./openapi/index.html
    theme:
      sidebar:
        textColor: "#d5dae6"
        activeBgColor: "#07489e"
        backgroundColor: "#05326d"
        activeTextColor: "#FFFFFF"
      typography:
        code:
          fontFamily: "Fira Code, monospace"
          fontSize: "13px"
          backgroundColor: "rgba(38, 50, 56, 0.05)"
          color: "#e53935"
        headings:
          fontFamily: "Lato, sans-serif"
        fontFamily: "Lato, sans-serif"
      colors:
        primary:
          main: "#32329f"
