---
version: '3'
services:
  test-db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_DB=postcodeio_testing
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postcodesio
    ports:
      - "5432:5432"

