FROM buildpack-deps:curl AS dump

COPY latest /tmp/latest

RUN mkdir -p /out && \
    curl -o /out/01-postcodesiodata.sql.gz $(cat /tmp/latest)

FROM postgis/postgis:18-3.6

COPY docker/postgresql.conf /etc/postgresql/postgresql.conf
COPY docker/postgis.sql /docker-entrypoint-initdb.d/00-postgis.sql
COPY --from=dump /out/01-postcodesiodata.sql.gz /docker-entrypoint-initdb.d/01-postcodesiodata.sql.gz
COPY docker/prewarm.sql /docker-entrypoint-initdb.d/02-prewarm.sql

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
