import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
import sidebar from "./docs/api/sidebar";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  openApiSidebar: [
    {
      link: {
        type: "generated-index",
        slug: "/api",
      },
      type: "category",
      label: "API",
      items: sidebar,
    },
  ],

  // But you can create a sidebar manually
  docsSidebar: [
    "overview",
    "self-host",
    "libraries",
    "about",
    {
      type: "category",
      label: "Postcodes",
      collapsed: true,
      items: [
        "postcode/schema",
        "postcode/lookup",
        "postcode/query",
        "postcode/bulk",
        "postcode/random",
        "postcode/autocomplete",
        "postcode/reverse-geocode",
        "postcode/bulk-reverse-geocode",
      ],
    },
    {
      type: "category",
      label: "Outward Codes",
      collapsed: true,
      items: [
        "outcode/schema",
        "outcode/lookup",
        "outcode/reverse-geocode",
        "outcode/nearest",
      ],
    },
    {
      type: "category",
      label: "Places",
      collapsed: true,
      items: ["place/schema", "place/lookup", "place/query", "place/random"],
    },
    {
      type: "category",
      label: "Terminated Postcodes",
      collapsed: true,
      items: ["terminated-postcode/schema", "terminated-postcode/lookup"],
    },
    {
      type: "category",
      label: "Scottish Postcodes",
      collapsed: true,
      items: ["scottish-postcode/schema", "scottish-postcode/lookup"],
    },
  ],
};

export default sidebars;
