import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docsSidebar: [
    "overview",
    "self-host",
    {
      type: "category",
      label: "Available Data Fields",
      collapsed: false,
      items: [
        "data-fields/postcode",
        "data-fields/outcode",
        "data-fields/scottish",
        "data-fields/terminated",
        "data-fields/places",
      ],
    },
    {
      type: "category",
      label: "Methods",
      collapsed: false,
      items: [
        "methods/postcode-lookup",
        "methods/bulk-postcode-lookup",
        "methods/reverse-geocoding",
        "methods/bulk-reverse-geocoding",
        "methods/postcode-query",
        "methods/postcode-validation",
        "methods/nearest-postcode",
        "methods/postcode-autocomplete",
        "methods/random-postcode",
        "methods/outward-code-lookup",
        "methods/outcode-reverse-geocoding",
        "methods/nearest-outcode",
        "methods/scottish-postcode-lookup",
        "methods/terminated-postcode-lookup",
        "methods/place-lookup",
        "methods/place-query",
        "methods/random-place",
      ],
    },
  ],
};

export default sidebars;
