import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docsSidebar: [
    "overview",
    "self-host",
    {
      type: "category",
      label: "Postcodes",
      collapsed: false,
      items: [
        "postcode/schema",
        "postcode/lookup",
        "postcode/query",
        "postcode/bulk",
        "postcode/random",
        "postcode/autocomplete",
        "postcode/reverse-geocode",
        "postcode/bulk-reverse-geocode",
      ],
    },
    {
      type: "category",
      label: "Outward Codes",
      collapsed: false,
      items: [
        "outcode/schema",
        "outcode/lookup",
        "outcode/reverse-geocode",
        "outcode/nearest",
      ],
    },
    {
      type: "category",
      label: "Places",
      collapsed: false,
      items: [
        "place/schema",
        "place/lookup",
        "place/query",
        "place/random",
      ],
    },
    {
      type: "category",
      label: "Terminated Postcodes",
      collapsed: false,
      items: [
        "terminated-postcode/schema",
        "terminated-postcode/lookup",
      ],
    },
    {
      type: "category",
      label: "Scottish Postcodes",
      collapsed: false,
      items: [
        "scottish-postcode/schema",
        "scottish-postcode/lookup",
      ],
    },
  ],
};

export default sidebars;
